// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://glawbtxhhsyupbzvrgtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsYXdidHhoaHN5dXBienZyZ3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTAyMjYsImV4cCI6MjA3MDYyNjIyNn0.sdny7yMeSlIGfupmx_r33Z5awXiKpPfKxBhyyHRPio0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});